try:
    print(1/0)
except:
    print("예외가 발생했습니다.")